# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contestcategories',
            options={'verbose_name_plural': 'Contests categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(help_text='Public description of the category. Supports Markdown'),
        ),
        migrations.AlterField(
            model_name='contestcategories',
            name='contest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categories_list', to='contests.TaskBasedContest'),
        ),
    ]
