version: '2'

services:
  db:
    image: bitnami/postgresql
    env_file: ./production.env
    ports:
      - "5432:5432"
    restart: always
    volumes:
     - ./volumes/pgdata:/bitnami
  web:
    build:
      context: ../
      dockerfile: docker/web/Dockerfile
    env_file: ./production.env
    restart: always
    command: web
    depends_on:
      - db
      - memcached
    volumes:
      - ./volumes/upload:/upload
      - ./volumes/static:/static
      - ./volumes/contest_import:/contest_import
  memcached:
    image: memcached
    command: memcached -m 8192 -I 8388608
    restart: always
  nginx:
    image: nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./volumes/certificates:/certificates:ro
      - ./volumes/static:/var/www/static:ro
      - ./volumes/task-resources:/var/www/static-files:ro
