# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_visible_in_list',
        ),
    ]
