# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import drapo.common


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_is_visible_in_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite_hash',
            field=models.TextField(default=drapo.common.generate_random_secret_string, max_length=32),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Participants (should contain captain)', related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
