# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import drapo.common


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20160613_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite_hash',
            field=models.TextField(default=drapo.common.generate_random_secret_string, max_length=32, unique=True),
        ),
    ]
