# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstracttasksopeningpolicy',
            options={'verbose_name': 'Task opening policy', 'verbose_name_plural': 'Task opening policies'},
        ),
        migrations.AlterModelOptions(
            name='bycategoriestasksopeningpolicy',
            options={'verbose_name': 'Task opening policy: by categories', 'verbose_name_plural': 'Task opening policies: by categories'},
        ),
        migrations.AlterField(
            model_name='contest',
            name='registration_finish_time',
            field=models.DateTimeField(blank=True, help_text='Contest registration finish time, only for open and moderated registration', null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='registration_start_time',
            field=models.DateTimeField(blank=True, help_text='Contest registration start time, only for open and moderated registrations', null=True),
        ),
    ]
