# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20160718_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.TextField(help_text='Contest name', unique=True),
        ),
    ]
