# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20170412_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractparticipant',
            name='contest_finish_time',
            field=models.DateTimeField(blank=True, help_text='Contest finish time', null=True),
        ),
        migrations.AddField(
            model_name='abstractparticipant',
            name='contest_start_time',
            field=models.DateTimeField(blank=True, help_text='Contest start time', null=True),
        ),
    ]
