# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-18 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20180218_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Region name')),
                ('start_time', models.DateTimeField(help_text='Contest start time for this region')),
                ('finish_time', models.DateTimeField(help_text='Contest finish time for this region')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='contests.Contest')),
            ],
        ),
        migrations.RemoveField(
            model_name='abstractparticipant',
            name='contest_finish_time',
        ),
        migrations.RemoveField(
            model_name='abstractparticipant',
            name='contest_start_time',
        ),
        migrations.AddField(
            model_name='abstractparticipant',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.ContestRegion'),
        ),
    ]
