# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.AbstractChecker'),
        ),
        migrations.AlterField(
            model_name='task',
            name='statement_generator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.AbstractStatementGenerator'),
        ),
    ]
