# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160607_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexpchecker',
            name='flag_ignore_case',
            field=models.BooleanField(default=False, help_text="Python's re.IGNORECASE (re.I)"),
        ),
    ]
