# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20160613_1427'),
        ('tasks', '0003_regexpchecker_flag_ignore_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_tasks', to='contests.Contest')),
                ('tasks', sortedm2m.fields.SortedManyToManyField(help_text=None, to='tasks.Task')),
            ],
        ),
    ]
