# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_contesttasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='', help_text='Shows on tasks page. Supports Markdown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', help_text='Shows on tasks page', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contesttasks',
            name='contest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_list', to='contests.Contest'),
        ),
    ]
