# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0003_auto_20160613_1427'),
        ('tasks', '0006_remove_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('public_comment', models.TextField(blank=True)),
                ('private_comment', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='contests.Contest')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='contests.AbstractParticipant')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tasks.Task')),
            ],
        ),
    ]
