# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20160613_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='textstatementgenerator',
            name='title',
            field=models.TextField(default='', help_text='Markdown with substitutes'),
            preserve_default=False,
        ),
    ]
