# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 19:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_textstatementgenerator_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 13, 19, 48, 54, 286136, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 13, 19, 48, 57, 519673, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
