# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='name',
            field=models.CharField(default='', help_text='File name. Visible to participants', max_length=1000),
            preserve_default=False,
        ),
    ]
