# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20160718_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualopenedtask',
            name='participant',
            field=models.ForeignKey(default=None, help_text='Set NULL to open task for everyone', null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.AbstractParticipant'),
        ),
    ]
