# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20160718_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTasksOpenedOpeningPolicy',
            fields=[
                ('abstracttasksopeningpolicy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.AbstractTasksOpeningPolicy')),
            ],
            options={
                'verbose_name_plural': 'Task opening policies: all',
                'verbose_name': 'Task opening policy: all',
            },
            bases=('tasks.abstracttasksopeningpolicy',),
        ),
        migrations.AlterModelOptions(
            name='manualtasksopeningpolicy',
            options={'verbose_name': 'Task opening policy: manual', 'verbose_name_plural': 'Task opening policies: manual'},
        ),
    ]
