# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20160729_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePyChecker',
            fields=[
                ('abstractchecker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.AbstractChecker')),
                ('source', models.TextField(help_text='Python source code. Must contain function check(attempt, context)')),
            ],
            options={
                'abstract': False,
            },
            bases=('tasks.abstractchecker',),
        ),
    ]
