# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-09 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_simplepychecker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Shows on tasks page', max_length=100, unique=True),
        ),
    ]
