# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20170409_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
