# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20160718_1313'),
        ('tasks', '0018_taskfile_is_private'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskfile',
            unique_together=set([('task', 'participant', 'name')]),
        ),
    ]
