# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20170412_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePyStatementGenerator',
            fields=[
                ('abstractstatementgenerator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.AbstractStatementGenerator')),
                ('source', models.TextField(help_text='Python source code. Must contain function generate(context)')),
            ],
            options={
                'abstract': False,
            },
            bases=('tasks.abstractstatementgenerator',),
        ),
    ]
