# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20170412_2032'),
        ('tasks', '0020_simplepystatementgenerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_plagiarized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='plagiarized_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.AbstractParticipant'),
        ),
    ]
