# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-23 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20180223_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeTasksOpeningPolicy',
            fields=[
                ('abstracttasksopeningpolicy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.AbstractTasksOpeningPolicy')),
            ],
            options={
                'verbose_name_plural': 'Task opening policies: welcome',
                'verbose_name': 'Task opening policy: welcome',
            },
            bases=('tasks.abstracttasksopeningpolicy',),
        ),
    ]
